// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NeuroStrokeCare.infrastructure.Context;

#nullable disable

namespace NeuroStrokeCare.infrastructure.Migrations
{
    [DbContext(typeof(NeuroFlowDbContext))]
    [Migration("20261002070000_AddStaffProfileFields")]
    partial class AddStaffProfileFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("NeuroStrokeCare.Data.AuditLogModel.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("NeuroStrokeCare.Data.Entities.ASPECTSAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssessedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AssessedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("C")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentState")
                        .HasColumnType("int");

                    b.Property<int>("I")
                        .HasColumnType("int");

                    b.Property<int>("IC")
                        .HasColumnType("int");

                    b.Property<int>("M1")
                        .HasColumnType("int");

                    b.Property<int>("M2")
                        .HasColumnType("int");

                    b.Property<int>("M3")
                        .HasColumnType("int");

                    b.Property<int>("M4")
                        .HasColumnType("int");

                    b.Property<int>("M5")
                        .HasColumnType("int");

                    b.Property<int>("M6")
                        .HasColumnType("int");

                    b.Property<int>("P")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AdmissionId")
                        .IsUnique();

                    b.HasIndex("AssessedById");

                    b.ToTable("ASPECTSAssessments");
                });

            modelBuilder.Entity("NeuroStrokeCare.Data.Entities.Admission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AdmissionTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AdmittedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CTADone")
                        .HasColumnType("bit");

                    b.Property<string>("CTAFindings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CTDone")
                        .HasColumnType("bit");

                    b.Property<string>("CTFindings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentState")
                        .HasColumnType("int");

                    b.Property<string>("DischargeNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DischargeTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MRIDone")
                        .HasColumnType("bit");

                    b.Property<string>("MRIFindings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrokeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StrokeTypeSetAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("StrokeTypeSetById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ThrombolysisDoseMg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ThrombolysisDrug")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ThrombolysisGivenAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ThrombolysisRecordedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AdmittedById");

                    b.HasIndex("BedId")
                        .IsUnique()
                        .HasFilter("[BedId] IS NOT NULL");

                    b.HasIndex("PatientId")
                        .IsUnique()
                        .HasFilter("[DischargeTime] IS NULL AND [CurrentState] = 1");

                    b.HasIndex("StrokeTypeSetById");

                    b.ToTable("Admissions");
                });

            modelBuilder.Entity("NeuroStrokeCare.Data.Entities.Assessments.BradenAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Activity")
                        .HasColumnType("int");

                    b.Property<Guid>("AdmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssessedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AssessedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentState")
                        .HasColumnType("int");

                    b.Property<int>("FrictionShear")
                        .HasColumnType("int");

                    b.Property<int>("Mobility")
                        .HasColumnType("int");

                    b.Property<int>("Moisture")
                        .HasColumnType("int");

                    b.Property<int>("Nutrition")
                        .HasColumnType("int");

                    b.Property<int>("SensoryPerception")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AdmissionId")
                        .IsUnique();

                    b.HasIndex("AssessedById");

                    b.ToTable("BradenAssessments");
                });

            modelBuilder.Entity("NeuroStrokeCare.Data.Entities.Assessments.GCSAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssessedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AssessedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentState")
                        .HasColumnType("int");

                    b.Property<int>("EyeResponse")
                        .HasColumnType("int");

                    b.Property<int>("MotorResponse")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VerbalResponse")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdmissionId")
                        .IsUnique();

                    b.HasIndex("AssessedById");

                    b.ToTable("GCSAssessments");
                });

            modelBuilder.Entity("NeuroStrokeCare.Data.Entities.Assessments.GUSSAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssessedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AssessedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentState")
                        .HasColumnType("int");

                    b.Property<int?>("LiquidScore")
                        .HasColumnType("int");

                    b.Property<bool>("NoDrooling")
                        .HasColumnType("bit");

                    b.Property<bool>("NoVoiceChange")
                        .HasColumnType("bit");

                    b.Property<bool>("SalivaSwallowSuccessful")
                        .HasColumnType("bit");

                    b.Property<int?>("SemisolidScore")
                        .HasColumnType("int");

                    b.Property<int?>("SolidScore")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Vigilance")
                        .HasColumnType("bit");

                    b.Property<bool>("VoluntaryCough")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AdmissionId")
                        .IsUnique();

                    b.HasIndex("AssessedById");

                    b.ToTable("GUSSAssessments");
                });

            modelBuilder.Entity("NeuroStrokeCare.Data.Entities.Assessments.MorseAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AmbulatoryAid")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssessedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AssessedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentState")
                        .HasColumnType("int");

                    b.Property<int>("Gait")
                        .HasColumnType("int");

                    b.Property<bool>("HistoryOfFalling")
                        .HasColumnType("bit");

                    b.Property<bool>("IVOrHeparinLock")
                        .HasColumnType("bit");

                    b.Property<bool>("MentalStatus")
                        .HasColumnType("bit");

                    b.Property<bool>("SecondaryDiagnosis")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AdmissionId")
                        .IsUnique();

                    b.HasIndex("AssessedById");

                    b.ToTable("MorseAssessments");
                });

            modelBuilder.Entity("NeuroStrokeCare.Data.Entities.Bed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BedNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentState")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WardId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BedNumber")
                        .IsUnique();

                    b.HasIndex("WardId");

                    b.ToTable("Beds");
                });

            modelBuilder.Entity("NeuroStrokeCare.Data.Entities.CanadianTIAAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssessedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AssessedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AtrialFibrillationOnECG")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentState")
                        .HasColumnType("int");

                    b.Property<bool>("DiastolicBPOver110")
                        .HasColumnType("bit");

                    b.Property<bool>("DysarthriaOrAphasia")
                        .HasColumnType("bit");

                    b.Property<bool>("FirstTIAInLifetime")
                        .HasColumnType("bit");

                    b.Property<bool>("GaitDisturbance")
                        .HasColumnType("bit");

                    b.Property<bool>("GlucoseOver15")
                        .HasColumnType("bit");

                    b.Property<bool>("HistoryCarotidStenosis")
                        .HasColumnType("bit");

                    b.Property<bool>("HistoryOfVertigo")
                        .HasColumnType("bit");

                    b.Property<bool>("InfarctionOnCT")
                        .HasColumnType("bit");

                    b.Property<bool>("OnAntiplateletTherapy")
                        .HasColumnType("bit");

                    b.Property<bool>("PlateletOver400")
                        .HasColumnType("bit");

                    b.Property<bool>("SymptomsOver10Min")
                        .HasColumnType("bit");

                    b.Property<bool>("UnilateralWeakness")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AdmissionId")
                        .IsUnique();

                    b.HasIndex("AssessedById");

                    b.ToTable("CanadianTIAAssessments");
                });

            modelBuilder.Entity("NeuroStrokeCare.Data.Entities.DoorTiming", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CTRecordedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentState")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DoorToCT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DoorToGroin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DoorToNeedle")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Er_StrokeArrival")
                        .HasColumnType("datetime2");

                    b.Property<string>("GroinRecordedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NeedleRecordedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AdmissionId")
                        .IsUnique();

                    b.ToTable("DoorTimings");
                });

            modelBuilder.Entity("NeuroStrokeCare.Data.Entities.FollowUpNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentState")
                        .HasColumnType("int");

                    b.Property<int>("NoteType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AdmissionId");

                    b.ToTable("FollowUpNotes");
                });

            modelBuilder.Entity("NeuroStrokeCare.Data.Entities.ICHAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AgeScore")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssessedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AssessedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentState")
                        .HasColumnType("int");

                    b.Property<int>("GCSScore")
                        .HasColumnType("int");

                    b.Property<decimal>("ICHVolumeMl")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IVHPresent")
                        .HasColumnType("bit");

                    b.Property<bool>("InfratentorialOrigin")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AdmissionId")
                        .IsUnique();

                    b.HasIndex("AssessedById");

                    b.ToTable("ICHAssessments");
                });

            modelBuilder.Entity("NeuroStrokeCare.Data.Entities.LabResults", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ALT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AST")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("AdmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Creatinine")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CurrentState")
                        .HasColumnType("int");

                    b.Property<bool?>("ECGAtrialFibrillation")
                        .HasColumnType("bit");

                    b.Property<decimal?>("GlucoseMmol")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("HbA1c")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Hemoglobin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("INR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("LDL")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Platelets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Potassium")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RecordedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Sodium")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("aPTT")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AdmissionId")
                        .IsUnique();

                    b.HasIndex("RecordedById");

                    b.ToTable("LabResultsSet");
                });

            modelBuilder.Entity("NeuroStrokeCare.Data.Entities.NIHSSAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssessedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AssessedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BestGaze")
                        .HasColumnType("int");

                    b.Property<int>("BestLanguage")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentState")
                        .HasColumnType("int");

                    b.Property<int>("Dysarthria")
                        .HasColumnType("int");

                    b.Property<int>("Extinction")
                        .HasColumnType("int");

                    b.Property<int>("FacialPalsy")
                        .HasColumnType("int");

                    b.Property<int>("LOC")
                        .HasColumnType("int");

                    b.Property<int>("LOCCommands")
                        .HasColumnType("int");

                    b.Property<int>("LOCQuestions")
                        .HasColumnType("int");

                    b.Property<int>("LimbAtaxia")
                        .HasColumnType("int");

                    b.Property<int>("MotorArmLeft")
                        .HasColumnType("int");

                    b.Property<int>("MotorArmRight")
                        .HasColumnType("int");

                    b.Property<int>("MotorLegLeft")
                        .HasColumnType("int");

                    b.Property<int>("MotorLegRight")
                        .HasColumnType("int");

                    b.Property<int>("Sensory")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Visual")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdmissionId")
                        .IsUnique();

                    b.HasIndex("AssessedById");

                    b.ToTable("NIHSSAssessments");
                });

            modelBuilder.Entity("NeuroStrokeCare.Data.Entities.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChiefComplaint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentState")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("NationalId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("NeuroStrokeCare.Data.Entities.Ward", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentState")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalBeds")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Wards");
                });

            modelBuilder.Entity("NeuroStrokeCare.Data.UserApplication.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AcademicDegree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRootSuperAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NationalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Profession")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestedRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("NeuroStrokeCare.Data.UserApplication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("NeuroStrokeCare.Data.UserApplication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeuroStrokeCare.Data.UserApplication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("NeuroStrokeCare.Data.UserApplication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NeuroStrokeCare.Data.Entities.ASPECTSAssessment", b =>
                {
                    b.HasOne("NeuroStrokeCare.Data.Entities.Admission", "Admission")
                        .WithOne("ASPECTSAssessment")
                        .HasForeignKey("NeuroStrokeCare.Data.Entities.ASPECTSAssessment", "AdmissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NeuroStrokeCare.Data.UserApplication.ApplicationUser", "AssessedBy")
                        .WithMany()
                        .HasForeignKey("AssessedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admission");

                    b.Navigation("AssessedBy");
                });

            modelBuilder.Entity("NeuroStrokeCare.Data.Entities.Admission", b =>
                {
                    b.HasOne("NeuroStrokeCare.Data.UserApplication.ApplicationUser", "AdmittedBy")
                        .WithMany()
                        .HasForeignKey("AdmittedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NeuroStrokeCare.Data.Entities.Bed", "Bed")
                        .WithOne("CurrentAdmission")
                        .HasForeignKey("NeuroStrokeCare.Data.Entities.Admission", "BedId");

                    b.HasOne("NeuroStrokeCare.Data.Entities.Patient", "Patient")
                        .WithMany("Admissions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NeuroStrokeCare.Data.UserApplication.ApplicationUser", "StrokeTypeSetBy")
                        .WithMany()
                        .HasForeignKey("StrokeTypeSetById");

                    b.Navigation("AdmittedBy");

                    b.Navigation("Bed");

                    b.Navigation("Patient");

                    b.Navigation("StrokeTypeSetBy");
                });

            modelBuilder.Entity("NeuroStrokeCare.Data.Entities.Assessments.BradenAssessment", b =>
                {
                    b.HasOne("NeuroStrokeCare.Data.Entities.Admission", "Admission")
                        .WithOne("BradenAssessment")
                        .HasForeignKey("NeuroStrokeCare.Data.Entities.Assessments.BradenAssessment", "AdmissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NeuroStrokeCare.Data.UserApplication.ApplicationUser", "AssessedBy")
                        .WithMany()
                        .HasForeignKey("AssessedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admission");

                    b.Navigation("AssessedBy");
                });

            modelBuilder.Entity("NeuroStrokeCare.Data.Entities.Assessments.GCSAssessment", b =>
                {
                    b.HasOne("NeuroStrokeCare.Data.Entities.Admission", "Admission")
                        .WithOne("GCSAssessment")
                        .HasForeignKey("NeuroStrokeCare.Data.Entities.Assessments.GCSAssessment", "AdmissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NeuroStrokeCare.Data.UserApplication.ApplicationUser", "AssessedBy")
                        .WithMany()
                        .HasForeignKey("AssessedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admission");

                    b.Navigation("AssessedBy");
                });

            modelBuilder.Entity("NeuroStrokeCare.Data.Entities.Assessments.GUSSAssessment", b =>
                {
                    b.HasOne("NeuroStrokeCare.Data.Entities.Admission", "Admission")
                        .WithOne("GUSSAssessment")
                        .HasForeignKey("NeuroStrokeCare.Data.Entities.Assessments.GUSSAssessment", "AdmissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NeuroStrokeCare.Data.UserApplication.ApplicationUser", "AssessedBy")
                        .WithMany()
                        .HasForeignKey("AssessedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admission");

                    b.Navigation("AssessedBy");
                });

            modelBuilder.Entity("NeuroStrokeCare.Data.Entities.Assessments.MorseAssessment", b =>
                {
                    b.HasOne("NeuroStrokeCare.Data.Entities.Admission", "Admission")
                        .WithOne("MorseAssessment")
                        .HasForeignKey("NeuroStrokeCare.Data.Entities.Assessments.MorseAssessment", "AdmissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NeuroStrokeCare.Data.UserApplication.ApplicationUser", "AssessedBy")
                        .WithMany()
                        .HasForeignKey("AssessedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admission");

                    b.Navigation("AssessedBy");
                });

            modelBuilder.Entity("NeuroStrokeCare.Data.Entities.Bed", b =>
                {
                    b.HasOne("NeuroStrokeCare.Data.Entities.Ward", "Ward")
                        .WithMany("Beds")
                        .HasForeignKey("WardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("NeuroStrokeCare.Data.Entities.CanadianTIAAssessment", b =>
                {
                    b.HasOne("NeuroStrokeCare.Data.Entities.Admission", "Admission")
                        .WithOne("CanadianTIAAssessment")
                        .HasForeignKey("NeuroStrokeCare.Data.Entities.CanadianTIAAssessment", "AdmissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NeuroStrokeCare.Data.UserApplication.ApplicationUser", "AssessedBy")
                        .WithMany()
                        .HasForeignKey("AssessedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admission");

                    b.Navigation("AssessedBy");
                });

            modelBuilder.Entity("NeuroStrokeCare.Data.Entities.DoorTiming", b =>
                {
                    b.HasOne("NeuroStrokeCare.Data.Entities.Admission", "Admission")
                        .WithOne("DoorTiming")
                        .HasForeignKey("NeuroStrokeCare.Data.Entities.DoorTiming", "AdmissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admission");
                });

            modelBuilder.Entity("NeuroStrokeCare.Data.Entities.FollowUpNote", b =>
                {
                    b.HasOne("NeuroStrokeCare.Data.Entities.Admission", "Admission")
                        .WithMany()
                        .HasForeignKey("AdmissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admission");
                });

            modelBuilder.Entity("NeuroStrokeCare.Data.Entities.ICHAssessment", b =>
                {
                    b.HasOne("NeuroStrokeCare.Data.Entities.Admission", "Admission")
                        .WithOne("ICHAssessment")
                        .HasForeignKey("NeuroStrokeCare.Data.Entities.ICHAssessment", "AdmissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NeuroStrokeCare.Data.UserApplication.ApplicationUser", "AssessedBy")
                        .WithMany()
                        .HasForeignKey("AssessedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admission");

                    b.Navigation("AssessedBy");
                });

            modelBuilder.Entity("NeuroStrokeCare.Data.Entities.LabResults", b =>
                {
                    b.HasOne("NeuroStrokeCare.Data.Entities.Admission", "Admission")
                        .WithOne("LabResults")
                        .HasForeignKey("NeuroStrokeCare.Data.Entities.LabResults", "AdmissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NeuroStrokeCare.Data.UserApplication.ApplicationUser", "RecordedBy")
                        .WithMany()
                        .HasForeignKey("RecordedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admission");

                    b.Navigation("RecordedBy");
                });

            modelBuilder.Entity("NeuroStrokeCare.Data.Entities.NIHSSAssessment", b =>
                {
                    b.HasOne("NeuroStrokeCare.Data.Entities.Admission", "Admission")
                        .WithOne("NIHSSAssessment")
                        .HasForeignKey("NeuroStrokeCare.Data.Entities.NIHSSAssessment", "AdmissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NeuroStrokeCare.Data.UserApplication.ApplicationUser", "AssessedBy")
                        .WithMany()
                        .HasForeignKey("AssessedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admission");

                    b.Navigation("AssessedBy");
                });

            modelBuilder.Entity("NeuroStrokeCare.Data.Entities.Patient", b =>
                {
                    b.HasOne("NeuroStrokeCare.Data.UserApplication.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("NeuroStrokeCare.Data.Entities.Admission", b =>
                {
                    b.Navigation("ASPECTSAssessment");

                    b.Navigation("BradenAssessment");

                    b.Navigation("CanadianTIAAssessment");

                    b.Navigation("DoorTiming")
                        .IsRequired();

                    b.Navigation("GCSAssessment");

                    b.Navigation("GUSSAssessment");

                    b.Navigation("ICHAssessment");

                    b.Navigation("LabResults");

                    b.Navigation("MorseAssessment");

                    b.Navigation("NIHSSAssessment")
                        .IsRequired();
                });

            modelBuilder.Entity("NeuroStrokeCare.Data.Entities.Bed", b =>
                {
                    b.Navigation("CurrentAdmission");
                });

            modelBuilder.Entity("NeuroStrokeCare.Data.Entities.Patient", b =>
                {
                    b.Navigation("Admissions");
                });

            modelBuilder.Entity("NeuroStrokeCare.Data.Entities.Ward", b =>
                {
                    b.Navigation("Beds");
                });
#pragma warning restore 612, 618
        }
    }
}
